[package]
name = "numpad_driver"
version = "0.1.0"
edition = "2024"

[dependencies]
evdev-rs = "0.6.1"
i2cdev = "0.6.1"
libc = "0.2.174"
thiserror = "2.0.12"


[profile.superopt]
inherits = "release"
lto = "fat"
codegen-units = 1
